# Generated by Django 5.1.2 on 2025-01-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('standup_comedy_shows', 'Standup Comedy Shows'), ('music_concerts', 'Music Concerts'), ('festivals', 'Festivals'), ('party', 'Party')], default='standup_comedy_shows', max_length=20),
        ),
    ]
