# Generated by Django 5.1.2 on 2025-01-27 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_slots',
            field=models.IntegerField(default=0, help_text='Number of available slots for the event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_per_person',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per person for attending the event.', max_digits=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='contact_number',
            field=models.BigIntegerField(blank=True, help_text='Enter a valid contact number without spaces or special characters.', null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(999999999999999)]),
        ),
        migrations.AddField(
            model_name='registration',
            name='persons',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registration',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of registration (calculated automatically).', max_digits=10, null=True),
        ),
    ]
