# Generated by Django 5.1.2 on 2025-01-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_event_available_slots_event_cost_per_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='assigned_user',
        ),
    ]
