# Generated by Django 5.1.2 on 2025-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_remove_event_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Enter a valid contact number without spaces or special characters.', max_length=255, null=True),
        ),
    ]
